#!/bin/bash

echo "🔧 Google Sheets Setup Helper"
echo "สำหรับอีเมล: nattapong05032535@gmail.com"
echo "======================================"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  File .env already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled"
        exit 1
    fi
fi

# Check if JSON file path is provided
if [ -z "$1" ]; then
    echo "📝 Please provide the path to your Service Account JSON key file"
    echo ""
    echo "Usage:"
    echo "  ./scripts/setup-google-sheets.sh <path-to-json-file>"
    echo ""
    echo "Example:"
    echo "  ./scripts/setup-google-sheets.sh ~/Downloads/restaurant-management-xxxxx.json"
    exit 1
fi

JSON_FILE="$1"

if [ ! -f "$JSON_FILE" ]; then
    echo "❌ Error: File not found: $JSON_FILE"
    exit 1
fi

echo "📂 Reading JSON file: $JSON_FILE"
echo ""

# Extract values from JSON using Node.js
NODE_SCRIPT=$(cat << 'EOF'
const fs = require('fs');
const jsonPath = process.argv[1];

try {
  const jsonContent = fs.readFileSync(jsonPath, 'utf8');
  const jsonData = JSON.parse(jsonContent);
  
  if (!jsonData.client_email || !jsonData.private_key) {
    console.error('ERROR: Invalid JSON file');
    process.exit(1);
  }
  
  const privateKey = jsonData.private_key.replace(/\n/g, '\\n');
  
  console.log(JSON.stringify({
    email: jsonData.client_email,
    privateKey: privateKey
  }));
} catch (error) {
  console.error('ERROR:', error.message);
  process.exit(1);
}
EOF
)

# Run Node.js script
JSON_RESULT=$(node -e "$NODE_SCRIPT" "$JSON_FILE" 2>&1)

if [ $? -ne 0 ]; then
    echo "❌ Error reading JSON file: $JSON_RESULT"
    exit 1
fi

SERVICE_EMAIL=$(echo "$JSON_RESULT" | node -e "const d=JSON.parse(require('fs').readFileSync(0, 'utf-8')); console.log(d.email)")
PRIVATE_KEY=$(echo "$JSON_RESULT" | node -e "const d=JSON.parse(require('fs').readFileSync(0, 'utf-8')); console.log(d.privateKey)")

echo "✅ Service Account Email: $SERVICE_EMAIL"
echo ""

# Ask for Spreadsheet ID
echo "📊 Please enter your Google Spreadsheet ID:"
echo "   (You can find it in the URL: https://docs.google.com/spreadsheets/d/SPREADSHEET_ID/edit)"
read -p "Spreadsheet ID: " SPREADSHEET_ID

if [ -z "$SPREADSHEET_ID" ]; then
    echo "❌ Error: Spreadsheet ID cannot be empty"
    exit 1
fi

# Create .env file
cat > .env << EOF
# Google Sheets API Configuration
# สำหรับอีเมล: nattapong05032535@gmail.com
# Generated by setup-google-sheets.sh

GOOGLE_SERVICE_ACCOUNT_EMAIL=$SERVICE_EMAIL
GOOGLE_PRIVATE_KEY="$PRIVATE_KEY"
GOOGLE_SPREADSHEET_ID=$SPREADSHEET_ID

# API Configuration
PORT=3001

# Frontend Configuration
NEXT_PUBLIC_API_URL=http://localhost:3001
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "📋 Next steps:"
echo "   1. Make sure you've shared your Google Sheet with: $SERVICE_EMAIL"
echo "   2. Run: cd api && pnpm run create-sheets"
echo "   3. Run: cd api && pnpm run check-setup"
echo "   4. Start the app: docker-compose up --build"
echo ""
echo "📖 For more details, see: SETUP_GOOGLE_SHEETS.md"
echo ""

